### ISSUE TITLE
wnameless/xe-temp

### ISSUE THREAD

**Issue by hrafique** [wnameless/docker-oracle-xe-11g#1]
Would you care to elaborate what's inside `wnameless/xe-temp`?

Thanks in advance

**Comment by finnjohnsen** [comment]
The missing wnameless/xe-temp is scaring me a little tbh.

- what is the FROM image of xe-temp?
- where does /tmp/oracle-xe_11.2.0-1.0_amd64.deb come from?

**Comment by wnameless** [comment]
The oracle-xe_11.2.0-1.0_amd64.deb is converted from the Linux tool Alien.

I am using it to avoid a bug which brings by the dockerfile command ADD.
For some reasons, it will fail while adding a large file(The bug might be
solved by now). I simply used scp to copy them into the image xe-temp, in
doing so, I could build this docker image from it.

2015-01-05 20:39 GMT+07:00 Finn Johnsen <notifications@github.com>:

**Comment by finnjohnsen** [comment]
Ok, thanks for your reply. Where can I find the full Dockerfile for xe-temp?

**Comment by wnameless** [comment]
I just made a new Dockfile. The xe-temp is not required anymore now.

2015-01-05 21:01 GMT+07:00 Finn Johnsen <notifications@github.com>:

**Comment by roytruelove** [comment]
This issue can be closed, yeah?

**Comment by corporate-gadfly** [comment]
Yup.
