### ISSUE TITLE
Feature - Upgrade to Oracle 12c

### ISSUE THREAD

**Issue by dalcantara** [wnameless/docker-oracle-xe-11g#106]
I'm using some paging functions that aren't available in oracle 11g.  Any plans to upgrade this to 12c?  If you need help I'm available but I warn you, I'm a oracle rookie and docker novice 😆

**Comment by wnameless** [comment]
No, it's not possible. There's no Oracle 12c express edition. But, if the 18c is coming out, I will make an update.
