### ISSUE TITLE
New commit image increase 2 Gb

### ISSUE THREAD

**Issue by PengBAI** [wnameless/docker-oracle-xe-11g#13]
Something I confuse is that when I change little things(for example, add a new user) in conteneur Oracle, then I commit this conteneur, why everytime it add 2 Gb into image? How can I avoid this ?
Thank you

**Comment by wnameless** [comment]
Don't commit directly, but add your new user by using the Dockerfile
instead.

BAI Peng <notifications@github.com> 於 2015年8月31日週一 下午8:21 寫道：

**Comment by PengBAI** [comment]
Sorry, it's container, not conteneur(French). Why Oracle container did this, I don't understand, is the  AUFS copy and update lots of files? In my use case, I update the Oracle container frequently. So the easiest way is commit after the changes.

**Comment by wnameless** [comment]
The new DB initialization feature may help.

**Comment by PengBAI** [comment]
Yes, I have forked your porject and have built my own image with DB initialization serveral months ago. 
Great job, thank you.
