### ISSUE TITLE
 remote access, if I have it installed on a vps?

### ISSUE THREAD

**Issue by 0noel0** [wnameless/docker-oracle-xe-11g#19]
It is not an issue, but rather a question. and if you can remotely access, which would have to configure?

**Comment by wnameless** [comment]
Please refer to

https://github.com/wnameless/docker-oracle-xe-11g/issues/7

**Comment by wnameless** [comment]
Or you can try the ORACLE_ALLOW_REMOTE option.
Please see the detail in the README.md.

**Comment by 0noel0** [comment]
Excellent, ORACLE_ALLOW_REMOTE option works perfect!! Thank you!!
