### ISSUE TITLE
how to wait on db

### ISSUE THREAD

**Issue by tomdavidson** [wnameless/docker-oracle-xe-11g#20]
It takes a while for the db to be ready for a connection, so when I start my stack with docker-compose, my client app breaks. I have set my client app to check and wait for the tcp listener, but it takes awhile longer for the database to actually be ready. What is a successful pattern of using wnameless/docker-oracle-xe-11g in a stack?

**Comment by rotilho** [comment]
Just add the dependency to https://hub.docker.com/r/aanand/wait/~/dockerfile/
