### ISSUE TITLE
Error when running SQL commands- ORA-01034: ORACLE not available

### ISSUE THREAD

**Issue by abrahamjaison01** [wnameless/docker-oracle-xe-11g#25]
Hi,

I just tried to use this oracle image but I am getting the following error for any command that I issue.
> ORA-01034: ORACLE not available

Following are the steps I did:
> `docker pull wnameless/docker-oracle-xe-11g`
> `docker run -d --name oracledb -p 41960:22 -p 49161:1521 wnameless/oracle-xe-11g`
> `ssh root@localhost -p 41960`

On providing the password, it logs in and then to the SQL prompt as well but can't do anything since then. The screen also shows `Connected to an idle instance`.! 
Could someone help me out with this immediately?

![oracledockererror](https://cloud.githubusercontent.com/assets/14936005/15812346/3d5b3048-2bd1-11e6-9f83-2d62debef29b.png)

Thanks very much!

**Comment by wnameless** [comment]
I just tried and everything was fine on my laptop.
Did you perform anything else after starting the container?

**Comment by abrahamjaison01** [comment]
No.. I did not do anything else after starting the container. Do you think it would be the problem with my laptop? I could not figure it out. 
However `docker pull mysql` is working fine. Can't figure out what is wrong and where!

**Comment by abrahamjaison01** [comment]
Hey.. Just a quick doubt! Is it necessary that we should have oracle installed in the host system to get this up and running?

**Comment by wnameless** [comment]
Nope, but it's only an express version. Keep it in mind.

abrahamjaison01 <notifications@github.com> 於 2016年6月17日週五 17:54 寫道：
