### ISSUE TITLE
unable to run init sql files

### ISSUE THREAD

**Issue by kkorada** [wnameless/docker-oracle-xe-11g#29]
i tried adding init.sql into docker, but it is not doing anything.

i tried creating users in that sql file, is it possible ?

my docker file is 

```
# Dockerfile
FROM wnameless/oracle-xe-11g

ADD init.sql /docker-entrypoint-initdb.d/
```

and my init.sql file is

```
CREATE user KAR_MASTER identified by KAR_ax;
GRANT create session to KAR_MASTER;
GRANT create table to KAR_MASTER;
GRANT CREATE CLUSTER to KAR_MASTER;
GRANT CREATE SYNONYM to KAR_MASTER;
GRANT CREATE VIEW to KAR_MASTER;
GRANT CREATE SEQUENCE to KAR_MASTER;
GRANT CREATE DATABASE LINK to KAR_MASTER;
GRANT CREATE PUBLIC DATABASE LINK to KAR_MASTER;
GRANT CREATE PROCEDURE to KAR_MASTER;
GRANT CREATE TRIGGER to KAR_MASTER;
GRANT CREATE MATERIALIZED VIEW to KAR_MASTER;
GRANT CREATE TYPE to KAR_MASTER;
GRANT CREATE OPERATOR to KAR_MASTER;
GRANT CREATE INDEXTYPE to KAR_MASTER;
GRANT CREATE DIMENSION to KAR_MASTER;
GRANT CREATE ANY CONTEXT to KAR_MASTER;
GRANT CREATE JOB to KAR_MASTER;
```

**Comment by wnameless** [comment]
Give some time to take a look.

Kalyan Sagar Korada <notifications@github.com> 於 2016年6月28日週二 15:22 寫道：

**Comment by kkorada** [comment]
ok sure

**Comment by kkorada** [comment]
i have seen that docker file
according to it
first startup.sh is executed at that point of time there are no files present in /docker-entrypoint-initdb.d
then `ADD init.sql /docker-entrypoint-initdb.d/ ` is executed so it is not reflecting in db i guess

**Comment by wnameless** [comment]
No matter where you place the CMD in dockerfile, it won't affect the image
building process.

The CMD simply sets up the default entrypoint arguments only.

Kalyan Sagar Korada <notifications@github.com> 於 2016年6月28日週二 20:50 寫道：

**Comment by wnameless** [comment]
I just tried to initialize DB by your sql script. Everything is fine on my laptop.
I am using the same Dockerfile that you provided.
How did you start your container?

**Comment by kkorada** [comment]
i have started my container using cmd
`sudo docker run -d -p 49160:22 -p 49161:1521 -e ORACLE_ALLOW_REMOTE=true <IMAGENAME>`
while the script is run any logs are printed, if yes how can i check them ?

**Comment by wnameless** [comment]
I simply login by ssh and run the sqlplus with your new username and password.

**Comment by kkorada** [comment]
yes it is working now,
previously i had some old image. i removed the image and pulled it again.

**Comment by lyt23** [comment]
my init.sql can't work around, user can create success, but table can't create, can u help me ,thanks a lot.
sqlplus system/oracle;

create user alexander identified by rtm;
alter user alexander account unlock;
grant create session to alexander;
grant dba to alexander;
GRANT CREATE USER,DROP USER,ALTER USER ,
   CREATE ANY VIEW , DROP ANY VIEW,
   EXP_FULL_DATABASE,IMP_FULL_DATABASE, 
   DBA,CONNECT,RESOURCE,CREATE SESSION  TO  alexander;

connect alexander/rtm;

CREATE TABLE PT_TD_GROUP 
(
   GROUP_ID             VARCHAR2(32)         NOT NULL,
   GROUP_NAME           VARCHAR2(64)         NOT NULL,
   GROUP_TYPE           INTEGER              NOT NULL,
   GROUP_PARENTID       VARCHAR2(32),
   GROUP_MTIME          TIMESTAMP            NOT NULL,
   GROUP_CTIME          TIMESTAMP            NOT NULL,
   GROUP_INDEX          INTEGER,
   GROUP_DESC           VARCHAR2(512),
   CONSTRAINT PK_PT_TD_GROUP PRIMARY KEY (GROUP_ID)
);
CREATE TABLE PT_TD_STAT 
(
   STAT_TASKID          VARCHAR2(32)         NOT NULL,
   TASK_NAME            VARCHAR2(64),
   STAT_STIME           DATE,
   STAT_FAILED          INTEGER,
   STAT_SUCCESS         INTEGER,
   STAT_RUNNING         INTEGER,
   STAT_AVGTIME         INTEGER,
   STAT_TOTALTIME       INTEGER,
   STAT_ETIME           DATE,
   STAT_MAXTIME         INTEGER,
   STAT_MINTIME         INTEGER,
   CONSTRAINT PK_PT_TD_STAT PRIMARY KEY (STAT_TASKID)
);
CREATE TABLE PT_TD_TASK 
(
   TASK_ID              VARCHAR2(32)         NOT NULL,
   TEC_ID               VARCHAR2(32)         NOT NULL,
   GROUP_ID             VARCHAR2(32)         NOT NULL,
   TASK_NAME            VARCHAR2(64)         NOT NULL,
   TASK_STATUS          VARCHAR2(64),
   TASK_TIMEOUT         INTEGER,
   TASK_TRGTYPE         VARCHAR2(64)         NOT NULL,
   TASK_STIME           DATE,
   TASK_ETIME           DATE,
   TASK_TRGTIMES        INTEGER,
   TASK_TRGINTERVAL     INTEGER,
   TASK_INTERVALUNIT    VARCHAR2(64),
   TASK_CRON            VARCHAR2(64),
   TASK_INDEX           INTEGER,
   TASK_CTIME           TIMESTAMP,
   TASK_MTIME           TIMESTAMP,
   TASK_DESC            VARCHAR2(512),
   CONSTRAINT PK_PT_TD_TASK PRIMARY KEY (TASK_ID)
);
