### ISSUE TITLE
ORA-24324: service handle not initialized

### ISSUE THREAD

**Issue by stef-pellegrino** [wnameless/docker-oracle-xe-11g#30]
**Update : 
My host is CentOS 7.0 64bit.
The image runs on Ubuntu. I think the issue is the difference of distrib.**

Do exactly what the doc. says, ie connecting to the container with ssh, then within :
sqlplus /nolog
connect sys as sysdba
startup
ORA-03113: end-of-file on communication channel
startup mount
ORA-24324: service handle not initialized

In log I can see that
Exception [type: SIGSEGV, Address not mapped to object]

**docker version:**

Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

**Comment by wnameless** [comment]
This is what I've got when running the command 'startup':
ORA-01081: cannot start already-running ORACLE - shut it down first

It's pretty reasonable, because the Oracle server was already running.

How did you start the container to get this error message?:
ORA-03113: end-of-file on communication channel

**Comment by stef-pellegrino** [comment]
Yes, I tried the same image with an Ubuntu host and it works.
My guess is that, basically,  my host is running under CentOS 7 64bit, and in that case, the oracle instance doesn't seem to start (only the listener)
