### ISSUE TITLE
Any difference which ojdbc is necessary?

### ISSUE THREAD

**Issue by stebiger** [wnameless/docker-oracle-xe-11g#31]
Hey,

I am currently trying to use that docker image with a jpa project.

http://www.oracle.com/technetwork/apps-tech/jdbc-112010-090769.html

Can you please tell me which exact version you have installed on that image?
Normally the newest ojdbc6.jar should work but I have some crazy problems using any of those ojdbc with that docker image - but I am fine connecting to the db with sqldeveloper so I am a bit confused.

Thanks for any hints.

**Comment by wnameless** [comment]
I installed the Oracle Database 11g Release 2 Express in this docker image.
Both ojdbc6 and ojdbc5 should work fine with this image and it really depends what JDK you are using now.
