### ISSUE TITLE
ORA-12545 because of tnsnames.ora entry

### ISSUE THREAD

**Issue by Hitokun** [wnameless/docker-oracle-xe-11g#32]
Not sure if something could be done, but when trying to explicitely connect to XE from docker itself I got ORA-12545 Connect failed because target host or object does not exist.
Checking with LSNRCTL I found the following
```
LSNRCTL> status XE
Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=33817b96c0aa)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)))
TNS-12545: Connect failed because target host or object does not exist
 TNS-12560: TNS:protocol adapter error
  TNS-00515: Connect failed because target host or object does not exist
   Linux Error: 110: Connection timed out
```
I can see docker is giving me a different  hostname: (d57f5951434b), so updating the file solved this. I don't know if this could or should be achieved programatically in the startup.sh

Im running elementary OS 0.3.2 64 bits (Ubuntu 14.04) with 14.04 xe image and custom DNS in the run parameters.

**Comment by wnameless** [comment]
It's weird. I do replace the hostname in the startup.sh.
How did you use this image?

**Comment by Hitokun** [comment]
From reading startup.sh, I had the same impression. 
I run the image like the example in the docker hub. I enabled ipv4 address forwarding
```
sysctl net.ipv4.conf.all.forwarding=1
```
 and set a  custom dns. It looks like this:
```
docker run -d -p --dns=10.x.x.x 49160:22 -p 49161:1521 wnameless/oracle-xe-11g:14.04.4
```
The OS where docker runs is Virtualized and the host pc is running through a VPN (im using the same DNS from the VPN in the docker run command.

**Comment by wnameless** [comment]
Can use the latest image instead of 14.04.4?
The 14.04.4 branch is a bit outdated.

**Comment by Hitokun** [comment]
Sure. 
I'll take a look at it tomorrow on my main pc :)

**Comment by Hitokun** [comment]
Tried the latest image and it seems to work fine, even on Ubuntu 14.04 based distros. Checked the latest commit to startup.sh https://github.com/wnameless/docker-oracle-xe-11g/commit/25c689e8139901e1d4173a702b77bc99c6afe8d5#diff-10d392d9a96a6d149734665c9e21618c and does exactly what it should now, even with my custom dns configuration:
```
root@671e899db66b:~# cat /u01/app/oracle/product/11.2.0/xe/network/admin/tnsnames.ora
# tnsnames.ora Network Configuration File:

XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 671e899db66b)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )

EXTPROC_CONNECTION_DATA =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_XE))
    )
    (CONNECT_DATA =
      (SID = PLSExtProc)
      (PRESENTATION = RO)
    )
  )

root@671e899db66b:~# sqlplus system/oracle@XE

SQL*Plus: Release 11.2.0.2.0 Production on Tue Jul 19 16:58:47 2016

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> 
```

Thanks a lot
