### ISSUE TITLE
Invalid installation folders

### ISSUE THREAD

**Issue by ianbram** [wnameless/docker-oracle-xe-11g#33]
I have just used the docker file to create a new container.
Once done and the docker run command issued I accessed the container via the docker exec -it {containerId} bash only to find that oracle was not running.  After much searching I discovered that the install had installed oracle to this path:
/u01/app/oracle/**oracle-product**  rather than where I expected it to be  eg:  /u01/app/oracle/**product**.

I modified the setup.sh script and moved all of the lines under:

dpkg --install /home/assets/oracle-xe_11.2.0-1.0_amd64.deb &&

and moved them to the top of the startup.sh script and added as the first command line:
**mv /u01/app/oracle/oracle-product /u01/app/oracle/product**

This fixed the problem and oracle now starts.

I am just curious as to why the installer installed to .../oracle/oracle-product rather than .../oracle/product

Ian

**Comment by wnameless** [comment]
I just checked the newest image of mine and there is no such problem you mentioned here.
I am a little confused now. Did you create your own image based on mine?

**Comment by ianbram** [comment]
Yes - I just downloaded everything from your github. Executed the "docker build" on the dockerfile and then tried to run a container based on the generated image.

**Comment by wnameless** [comment]
Could you try to run `docker pull wnameless/oracle-xe-11g` directly
