### ISSUE TITLE
sysdba

### ISSUE THREAD

**Issue by txdv** [wnameless/docker-oracle-xe-11g#34]
Is there a way to connect as sysdba? I need to grant the ability to access utl_file to the system user.

**Comment by wnameless** [comment]
Run sqlplus with sys/oracle or system/oracle

**Comment by bkmeneguello** [comment]
@wnameless why not run /docker-entrypoint-initdb.d/* sqlplus with
```
$ su -m oracle -c '$ORACLE_HOME/bin/sqlplus sys/oracle as sysdba @'"$f"
```
It should be a lot more userfull
