### ISSUE TITLE
Delete files after executing them

### ISSUE THREAD

**Issue by pzrinscak** [wnameless/docker-oracle-xe-11g#35]
Would it make sense to delete SQL scripts added to docker-entrypoint-initdb.d after executing them? That way they will not be executed twice when the same container is stopped and stared again.

**Comment by wnameless** [comment]
In my opinion, it should rely on the way you wrote the script.
If the script should be executed under certain conditions only, the script should check conditions by itself.

**Comment by juanrferia** [comment]
I have an automated exported SQL script I use to initialize the database. My expectation is this init script to be executed only once, for initialization purpose.
As a reference, please have a look to official MySQL docker image to see how it only executed the init scripts if the database is not initialized: 

https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh

You can see:
if [ ! -d "$DATADIR/mysql" ]; then
...
                 for f in /docker-entrypoint-initdb.d/*; do
			case "$f" in
				*.sh)     echo "$0: running $f"; . "$f" ;;
				*.sql)    echo "$0: running $f"; "${mysql[@]}" < "$f"; echo ;;
				*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${mysql[@]}"; echo ;;
				*)        echo "$0: ignoring $f" ;;
			esac
			echo
		done
...
fi
