### ISSUE TITLE
User Name and Password for the Web Console

### ISSUE THREAD

**Issue by sakhtar1979** [wnameless/docker-oracle-xe-11g#36]
Hi,
_This is not an issue per say rather a question_
Can you help with logging into Apex web console? I have tried sys/oracle and system/oracle but both won't work.

Thanks,
Shoaib

**Comment by li3p** [comment]
I have the same issue.

**Comment by wnameless** [comment]
First, go to https://your-node-ip-address/apex/
Enter following  information:
Workspace: INTERNAL
Username: ADMIN
password: oracle

Hope it helps
