### ISSUE TITLE
Create a Dockerfile which works with the original Oracle installer

### ISSUE THREAD

**Issue by digulla** [wnameless/docker-oracle-xe-11g#4]
The current image violates the [Oracle 11g Express license](http://www.oracle.com/technetwork/licenses/database-11g-express-license-459621.html) which prevents me from using your work.

Can you please create a second Dockerfile which contains the commands necessary to convert the RPM into the split DEB archive (which I can then copy out to replace the files you provide) or, even better, a Dockerfile which installs from the downloaded RPM (i.e. which contains the commands to convert the RPM to DEB, installs and then deletes the RPM and DEP archives).

**Comment by wnameless** [comment]
Hi,

I simply downloaded the oracle installer from oracle website and using the
Linux command "alien" to convert it from rpm to deb. The reason I used the
Linux command "split" to split the deb is because Github only allows files
which are under 100 mb to be uploaded.
Hope I answer your question.

WMW

digulla <notifications@github.com> 於 2015年4月7日 星期二寫道：

**Comment by digulla** [comment]
I see; when I run `alien`, it warns me that the RPM contains scripts. You ignored those (i.e. you didn't pass any specific options to `alien` which would enable an automatic conversion attempt), right?

**Comment by wnameless** [comment]
Actuallly you have to include all the scripts.

digulla <notifications@github.com> 於 2015年4月9日 星期四寫道：

**Comment by digulla** [comment]
Can you give me the exact command line which you used?

**Comment by wnameless** [comment]
alien --scripts -d oracle-xe-11.x.x-x.x.x86_64.rpm



digulla <notifications@github.com> 於 2015年4月9日 星期四寫道：

**Comment by digulla** [comment]
Thanks. I've taken all this information to create a script which allows you to offer a clean docker image. See https://gist.github.com/digulla/09fdc1e0ae920ab5cc46
