### ISSUE TITLE
ORA-01034: ORACLE not available on startup

### ISSUE THREAD

**Issue by bkolobara** [wnameless/docker-oracle-xe-11g#46]
Hi,

after I lunch the container with 2 sql files to initialize the db I get the following errors:

```
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
/usr/sbin/startup.sh: running /docker-entrypoint-initdb.d/1-create-tables.sql
SQL*Plus: Release 11.2.0.2.0 Production on Wed Dec 7 16:33:25 2016
Copyright (c) 1982, 2011, Oracle.  All rights reserved.
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0
Enter user-name: Enter password: 
ERROR:
ORA-01005: null password given; logon denied
Enter user-name: 
/usr/sbin/startup.sh: running /docker-entrypoint-initdb.d/1-insert-alerts.sql
SQL*Plus: Release 11.2.0.2.0 Production on Wed Dec 7 16:33:25 2016
Copyright (c) 1982, 2011, Oracle.  All rights reserved.
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0
Enter user-name: Enter password: 
ERROR:
ORA-01005: null password given; logon denied
Enter user-name: 
```

I start it with:
```
docker run -d -p 49160:22 -p 49161:1521 oracle
```

And I create oracle from this Dockerfile
```
FROM wnameless/oracle-xe-11g

# Initialise with testing data
ADD database_creation.sql /docker-entrypoint-initdb.d/1-create-tables.sql
ADD alerts.sql /docker-entrypoint-initdb.d/1-insert-alerts.sql
```

**Comment by mgreenwald-pm** [comment]
@bkolobara Did you find a solution to this issue?

**Comment by bkolobara** [comment]
Sadly no. I switched to https://hub.docker.com/r/sath89/oracle-12c/

**Comment by wnameless** [comment]
Can you provide your sql files? I would like to dig into this problem.

**Comment by mgreenwald-pm** [comment]
@wnameless I was mistaken, we do not `ADD any.sql` files in our Dockerfile. Thanks for your interest though.

**Comment by zoechen799** [comment]
Hi, I found the reason why got ORA-01034 and ORA-27101 on my side, It's because of selinux is turned on on host machine.  To fix it.
modify /etc/selinux/config on host machine
set SELINUX=enforcing to SELINUX=disabled

**Comment by mgreenwald-pm** [comment]
@zoechen799 Thanks, thats helpful.

**Comment by digulla** [comment]
This can also happen when the root disk is full. Some versions of Docker for Windows just allocate 20GB of disk space in the VirtualBox VM. See https://github.com/docker/toolbox/issues/157 and https://github.com/docker/toolbox/pull/203

If this is your problem, you can fix it by deleting the virtual machine with `docker-machine rm default` (**THAT WILL DELETE ALL YOUR DATA IN YOUR DOCKER IMAGES**) and recreate it with `docker-machine  create -d virtualbox --virtualbox-disk-size 1048576 default`. Or you can create a new virtual machine by giving a different name than `default`.

Note that this command will seem to be stuck in

    (default) Creating SSH key...

In the background, VBoxManage is formatting the virtual hard disk. That can take up to an hour. Be patient.
