### ISSUE TITLE
Image probably doesn't need SSL (suggestion)

### ISSUE THREAD

**Issue by MattFriedman** [wnameless/docker-oracle-xe-11g#49]
If I execute 

`docker exec -it <name_of_running_container> bash`

then I will have a shell on the running container. 

So, I don't see a need for ssh on this container and in general it is best to keep things as clean as possible and with as few running processes as possible. 

Just a suggestion that you can likely remove SSH from this image.

**Comment by wnameless** [comment]
I am totally agree with you. However I keep it because of some legacy issues. So far, I 've heard people using SSL to backup database and other tasks.

**Comment by MattFriedman** [comment]
It's your image, and quite useful, so thanks. I would just say to that point that if they're backing up over ssl it really isn't a good practice. they should be using a volume mount (-v) for the data onto the host machine, and backing up from that mounted directory. Nevertheless, thanks again.
