### ISSUE TITLE
Avoid long delay during SSH login

### ISSUE THREAD

**Issue by raffaeleguidi** [wnameless/docker-oracle-xe-11g#5]
Hi, may I suggest to add the following line to the dockerfile to disable DNS reverse lookup at SSH login time?

   echo "UseDNS no" >> /etch/ssh/sshd_config

Regards,
   R

**Comment by wnameless** [comment]
I am not sure about the consequences if I add this line. I will take some time to look it up. Thanks for sharing anyway.

**Comment by raffaeleguidi** [comment]
the issue is annoying but probably only in private datacenters with no DNS setup (such as ours). I've solved my problem creating my own dockerfile, of course based on yours - https://github.com/raffaeleguidi/dockerized-oracle-xe 

Many thanks for the great job

**Comment by brunowego** [comment]
+1
