### ISSUE TITLE
ORACLE not available when i run this image

### ISSUE THREAD

**Issue by Jason2002** [wnameless/docker-oracle-xe-11g#50]
hi team, i use this image to run a oracle container on centos 7, but when i run this, these error throw out, what mistake i made ?
### Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
/usr/sbin/startup.sh: ignoring /docker-entrypoint-initdb.d/*
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0
SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]

**Comment by gustavonalle** [comment]
I am seeing the same issue. It looks like something is broken in the `latest` tag. Using `16.04` should work

**Comment by IceSeaOnly** [comment]
Hi,I have the same problem with lastest docker on centos 7 those days,have you solved this problem?

**Comment by zoechen799** [comment]
Same as I. Anyone can take a look?

**Comment by zoechen799** [comment]
Hi, I found the reason why got ORA-01034 and ORA-27101 on my side, It's because of selinux is turned on on host machine.  To fix it.
modify /etc/selinux/config on host machine
set SELINUX=enforcing to SELINUX=disabled

**Comment by wnameless** [comment]
Thank you for this solution.

**Comment by hussamaladas** [comment]
i have the same problem and SELINUX=disabled but not work
