### ISSUE TITLE
Make log available on STDOUT

### ISSUE THREAD

**Issue by mrVanDalo** [wnameless/docker-oracle-xe-11g#51]
Is it possible to log to stdout? 
This will make it easy to see the logs using `docker log <container>`.

It would also be nice to be able to change the loglevel via environment variable.

**Comment by wnameless** [comment]
https://docs.docker.com/engine/admin/logging/view_container_logs/

Base on the official documentation, you can create a symbolic link for Oracle log file to stdout.

Hope it helps somehow.

**Comment by mrVanDalo** [comment]
true, but why not do it?
