### ISSUE TITLE
Listener does not know the SID xe (remote)

### ISSUE THREAD

**Issue by jradesenv** [wnameless/docker-oracle-xe-11g#55]
I'm using this commannd to start the oracle docker in an amazon ec2:
docker run -d -p 49160:22 -p 49161:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g  

But when i try to connect it in my develop machine sql developer, it says the listener does not currently know the SID xe.

I read about it happening when you try to connect from remote but i'm using the ORACLE_ALLOW_REMOTE X.X

anyone knows what can i do?

**Comment by herojhc** [comment]
I have the same problem @jradesenv

**Comment by herojhc** [comment]
> Hi, I found the reason why got ORA-01034 and ORA-27101 on my side, It's because of selinux is turned on on host machine. To fix it.
modify /etc/selinux/config on host machine
set SELINUX=enforcing to SELINUX=disabled

reboot 
@jradesenv

**Comment by Jack3364** [comment]
you cat enter:   sudo setenfore 0
that's ok for me!

**Comment by jradesenv** [comment]
thanks for the help guys, I already moved to amazon RDS, but if you say this is working now I will close it. Thanks again!
