### ISSUE TITLE
unlock xdb so user can login to http://.8080

### ISSUE THREAD

**Issue by leonsoft** [wnameless/docker-oracle-xe-11g#60]
Everything works except a minor issue that I was kept asked to input xdb password when login to http://.8080. 
This is fixed by following http://www.forumtopics.com/busobj/viewtopic.php?p=370684 as below. It can be resolved in the image.
ALTER USER XDB ACCOUNT UNLOCK;
ALTER USER XDB IDENTIFIED BY xdb;

**Comment by wnameless** [comment]
The XDB user can be activated now by passing an environment variable ORACLE_ENABLE_XDB=true in the docker RUN command.
