### ISSUE TITLE
setting disk_asynch_io = false improves rspec unit test elapsed time when running on Travis CI Trusty

### ISSUE THREAD

**Issue by yahonda** [wnameless/docker-oracle-xe-11g#61]
Thanks for providing useful Dockerfile to run Oracle XE 11g.  Oracle enhanced adapter unit tests at Travis CI rely on this Dockerfile.

This is not an issue but wanted to inform my experience. Recently Travis CI Ubuntu is migrating from Ubuntu Precise (12.04) to Ubuntu Trusty(14.04) then Oracle enhanced adapter unit tests elapsed time is getting slower.

* [CI on Travis getting slower on Trusty](https://github.com/rsim/oracle-enhanced/issues/1397)

I opened a support request with Travis CI and finally  this slowness has been resolved by setting `disk_asynch_io = false` 

* [Setting `disk_asynch_io` to `false` to address slow unit tests ](https://github.com/rsim/oracle-enhanced/pull/1413)

Here are elapsed time differences between these settings/OS version.

* [Trusty + disk_asynch_io = false](https://travis-ci.org/rsim/oracle-enhanced/builds/264455617)

CRuby about 4 min
JRuby about 7 min

* [Trusty + disk_async_io = true](https://travis-ci.org/rsim/oracle-enhanced/builds/259379061)

CRuby about 8 min
JRuby about 26 min

* [Precise + disk_asynch_io = true](https://travis-ci.org/rsim/oracle-enhanced/builds/258648463)

CRuby about 4 min
JRuby about 10 min

please feel free to close this issue since I just wanted to inform this parameter change.
Thanks.

**Comment by wnameless** [comment]
It can be achieved now by passing an environment variable ORACLE_DISABLE_ASYNCH_IO=true in the docker RUN command.

**Comment by yahonda** [comment]
Thank you.
