### ISSUE TITLE
System user's password expired (in grace period)

### ISSUE THREAD

**Issue by nutfox** [wnameless/docker-oracle-xe-11g#62]
This image used to work fine. A couple of days ago the init script for our database started throwing errors/warnings because the system user's password is about to expire in 7 (today, 22.08.2017) days. 

We worked around this by connecting as "sys as sysdba" and unlocking the system account.

Can the image be rebuilt with a non-expiring system account?

**Comment by wnameless** [comment]
I just release a new version with non-expiring system account by default.
If you want the password verification back, you can add ORACLE_PASSWORD_VERIFT=true variable while starting the image.
