### ISSUE TITLE
init scripts move causes failure for volumes

### ISSUE THREAD

**Issue by typekpb** [wnameless/docker-oracle-xe-11g#65]
since the commit: feadff2ee130ff704616db304fa7df1f07d29825 I have a problem, that script that I used for DB initialization propagated to container via volume now causes volume failure on startup.

my docker-compose chunk: 

	version: "3.0"
 
	services:   

  	oracle:
    	image: wnameless/oracle-xe-11g:latest
    	ports:
      	- "1522:1521"
      	- "8081:8080"
    	volumes:
      	- ./script/docker/oracle/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql

running `docker-compose up` results in:

    oracle_1    | mv: cannot move '/docker-entrypoint-initdb.d/create_user.sql' to '/docker-entrypoint-initdb.d.bak/create_user.sql': Device or resource busy    
    [secure]_oracle_1 exited with code 1

(full log: https://travis-ci.org/p6spy/p6spy/jobs/268948826 )

What would be the proper way to propagate the script to container? Obviously volume I used to use before is not working any more.

Honestly I don't consider modifying (in the particular case: moving to another location) init scripts a good idea, other DBs don't do that, as far as I can see:

 * mysql: https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh#L170
 * postgres: https://github.com/docker-library/postgres/blob/master/10/docker-entrypoint.sh#L126 

would you mind rolling back to original behaviour?

What was the motivation behind this change? Am I now forced to build new container (`FROM  wnameless/oracle-xe-11g` ... `ADD ./script/docker/oracle/create_user.sql /docker-entrypoint-initdb.d/
`) to support the init script functionality?

**Comment by wnameless** [comment]
This feature has been reverted. Please pull the image again.

**Comment by typekpb** [comment]
excelent, works OK now!
