### ISSUE TITLE
disable password expiration

### ISSUE THREAD

**Issue by stsymbal** [wnameless/docker-oracle-xe-11g#66]
The password_life_time is currently set to 180 which results in SYSTEM and custom users being locked out after 180 days. PASSWORD_VERIFY_FUNCTION=NULL doesn't seem to be enough if PASSWORD_LIFE_TIME is set to 180.

The workaround is to execute the following queries at the beginning of the init script, before any other users are created. It would be nice to have this address on the image level. Thank you!

```
alter profile DEFAULT limit password_life_time UNLIMITED;
alter user SYSTEM identified by oracle account unlock;
```

**Comment by wnameless** [comment]
Give me some time. I will take a try.

**Comment by wnameless** [comment]
It's been done. Please pull again. Thanks.
