### ISSUE TITLE
Repository wnameless/oracle-xe-11g not found

### ISSUE THREAD

**Issue by shaibazkhan** [wnameless/docker-oracle-xe-11g#70]
Hi there,

I am getting this error since morning any idea why?

`: repository wnameless/oracle-xe-11g not found: does not exist or no pull access` 

Also this link https://hub.docker.com/r/wnameless/oracle-xe-11g/ is giving 404

**Comment by donkeysharp** [comment]
we are getting the same error, it's breaking some of our things

**Comment by vasanth-mahendran** [comment]
Any reason why its shutdown? If there are no plans for bringing it up, please let us know so that we will plan for alternates

**Comment by Equim-chan** [comment]
At the moment we could only build the image on our own.
```bash
$ git clone https://github.com/wnameless/docker-oracle-xe-11g.git
$ cd docker-oracle-xe-11g
$ docker build -t wnameless/docker-oracle-xe-11g .
```

**Comment by wgriffiths** [comment]
If anyone is interested I have pushed the image to our docker hub account thebookpeople/oracle-xe-11g

**Comment by shaibazkhan** [comment]
@wgriffiths can you please post a link to docker hub?

**Comment by wgriffiths** [comment]
https://hub.docker.com/r/thebookpeople/oracle-xe-11g/

**Comment by nritholtz** [comment]
We are using this image across multiple CI pipelines/projects. 

I'd rather not make the change to another image, unless we know for sure that this will not be re-uploaded. Can we please have a clarification if this deletion was intentional?

**Comment by wnameless** [comment]
I have no idea that why my repository has been deleted. I am trying to bring it back ASAP.

**Comment by wnameless** [comment]
The repository is back. I still need to figure out why my repository on docker hub has been deleted for no reason. I guess there is a problem between Github and Docker hub during the automated build process. I am now not able to build image from Github directly, instead I have to push my images from local machine.

If anyone knows what happened behind those issues, please let me know.

**Comment by wnameless** [comment]
Interesting! The automated build is working now. What happened to Docker hub?

I think the only casualty I've got is that I lost all my stars on docker hub. So bad!
