### ISSUE TITLE
http://localhost:8080 not authorized

### ISSUE THREAD

**Issue by cmosguy** [wnameless/docker-oracle-xe-11g#71]
I enabled the ORACLE_ENABLE_XDB=true.  When I try to login on http://localhost:8080 and use username: XDB and password: xdb it does not authorize access.

What am I doing wrong?

**Comment by jenaye** [comment]
https://github.com/wnameless/docker-oracle-xe-11g/pull/73
i'm just waiting for a merge

**Comment by wnameless** [comment]
What's the docker machine you are using? It may refer to other ip address instead of localhost.

**Comment by wnameless** [comment]
The readme.md about XDB had been updated. Please take a look.

**Comment by irib** [comment]
Had the same issue, no auth was possible. following README.md is not working in my case. 

I had to use http://127.0.0.1:8080 instead of http://localhost:8080, and everything works fine

(I confirm my /etc/hosts contains the localhost entry)
