### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by gaea44** [wnameless/docker-oracle-xe-11g#88]
Hi,

I can connect database with sqldeveloper.
But when I try to connect with doctrine (database ORM for symfony and PHP), I have the following error :

`An exception occured in driver: ORA-12541: TNS:no listener`

Thanks for any help

**Comment by nethoncho** [comment]
What connect string are you using?
This works for me
```
docker run -d -p 8022:22 -p 1521:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g
sqlplus system/oracle@localhost/XE
```

**Comment by gaea44** [comment]
Hi,

Don't worry, this works now for me too.
Sorry, can't remember what's going wrong with my config, but now its ok.

**Comment by rsoliveira27** [comment]
> Hi,
> 
> Don't worry, this works now for me too.
> Sorry, can't remember what's going wrong with my config, but now its ok.

Hi! I'm having the same problem, what did you do to fix it? Thanks!!!
