### ISSUE TITLE
Password will expire soon!

### ISSUE THREAD

**Issue by phreakadelle** [wnameless/docker-oracle-xe-11g#89]
Since a few days we receive the error
``` 
ERROR:
ORA-28002: the password will expire within 7 days
``` 
when starting up the container. I assume that issue occurs because the base image hosted on docker-hub is now 6 month old. 

![image](https://user-images.githubusercontent.com/645665/38661719-12a2c2d8-3e32-11e8-9992-68a0d38fe27d.png)

May i ask you to rebuild your image and upload it again? Maybe also add a statement that the password does not expire.

**Comment by 38leinaD** [comment]
+1
same problem here

**Comment by wnameless** [comment]
But it's really weird because I did disable password expiration by default. However, I will check it again.

**Comment by phreakadelle** [comment]
Yeah... i've seen that. But it seems that it's not working. Maybe you need to alter the sys/system users explicit?

**Comment by wnameless** [comment]
The problem has been fixed. Both latest and 16.04 branches are rebuild. Please checkout the newest image.
