### ISSUE TITLE
How can I use sqlplus ?

### ISSUE THREAD

**Issue by xrobert35** [wnameless/docker-oracle-xe-11g#91]
Hello, 

My database seem to work fine,  but for more flexibility I would like to be able to use sqlplus.

I tried to find the sqlplus.sh  but with no success  /u01/app/oracle-product  and  /u01/app/oracle/product  are empty.  How can I do ?

thanks

**Comment by wnameless** [comment]
docker exec -it <your container id> bash

**Comment by xrobert35** [comment]
Ok it was simple my bad... sorry
