### ISSUE TITLE
how to increase the max memory  and sga ?

### ISSUE THREAD

**Issue by qq273681448** [wnameless/docker-oracle-xe-11g#92]
my server's memory is 16G,but the oracle container only use 1.5G memory,
i can't increase the memory ,and i'm very depressed.
thanks

**Comment by wnameless** [comment]
No, it's not possible with Oracle 11g "Express" which only allows 1g memory, 11g storage and 1 core cpu.

**Comment by qq273681448** [comment]
oh,shit,fuck oracle.
thanks for your answer.
