### ISSUE TITLE
Could you update the image with the latest apex 18.1

### ISSUE THREAD

**Issue by aymanwkh** [wnameless/docker-oracle-xe-11g#94]
run the image as expected, but after upgrading to apex 18.1 the
http://localhost:8080/apex/apex_admin becomes unavailable with "The connection was reset" error.
Any idea or Could you update the image with the latest apex 18.1?

**Comment by wnameless** [comment]
The new branch 18.04-apex has been     released. See the readme file first and then pull it.

**Comment by wnameless** [comment]
Working on it.
